version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ['sh', '/entrypoint.sh']
    environment:
      POSTGRES_DB: "courses"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - "db:postgres"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: "courses"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  worker:
    build: .
    environment:
      POSTGRES_DB: "courses"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    links:
      - "db:postgres"
    depends_on:
      - db
      - web