# Generated by Django 3.2.3 on 2021-05-25 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_professors', models.ManyToManyField(related_name='collaborated_courses', related_query_name='collaborated_courses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='available_courses', related_query_name='available_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
