# Generated by Django 3.2.3 on 2021-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='empty here', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='empty name', max_length=64),
            preserve_default=False,
        ),
    ]
