# Generated by Django 3.2.3 on 2021-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_auto_20210530_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyhomework',
            name='student_comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
